Interpreter now seems to make more progress with functions
- Previously:
```
[DEBUG] Parsing complete!

[DEBUG INT] Executing top-level statement
[DEBUG INT] `interpret()` called
[DEBUG INT] Matched: `AST_ASSIGNMENT`
[DEBUG INT] Interpreted node type: `0`
[DEBUG INT] Node is a number: `0.000000`
Error: Assignment node missing variable name.
Node type: 0
```
- Now:
```
[DEBUG] Parsing complete!

[DEBUG INT] Executing top-level statement
[DEBUG INT] `interpret()` called
[DEBUG INT] Matched: `AST_ASSIGNMENT`
[DEBUG INT] Interpreted node type: `0`
[DEBUG INT] Node is a number: `0.000000`
[DEBUG INT] Assignment variable name missing for node type: 0
[DEBUG] Execution complete!
flavor(84770,0x207bf8840) malloc: *** error for object 0xa: pointer being freed was not allocated
flavor(84770,0x207bf8840) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    84770 abort      ./flavor tests/test6.flv --debug
```

#60